name: tests_system

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run:  make
    - name: matrix_tests
      run: ./matrix_tests
    - name: gauss_tests
      run: ./gauss_tests 
    - name: reverse_matrix_tests
      run: ./reverse_matrix_tests
    - name: vectors_tests
      run: ./vectors_tests   
    
